version: '3'

services:
  bot:
    image: "duderman/trippybot:0.0.2"
    depends_on:
      - network
    links:
      - network
    env_file: .env
    restart:
      always
  network:
    image: "duderman/trippynet:0.0.2"
    restart:
      always
    ipc: shareable
