version: '3'

services:
  bot:
    build: ./bot
    depends_on:
      - network
    links:
      - network
    environment:
      - TELEGRAM_TOKEN
    restart:
      always
  network:
    build: ./network
    restart:
      always
