version: '3'

services:
  bot:
    build: ./bot
    depends_on:
      - network
    links:
      - network
    env_file: .env
    restart:
      always
  network:
    build: ./network
    restart:
      always
